image: atlassian/default-image:2

pipelines:
  branches:
    main:
      - step:
          name: Build
          image: node:18.19
          script:
            - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"🔧 Thunai Brain Build step started...\"}' $SLACK_WEBHOOK_URL"
            - echo "Starting npm install"
            - npm config set fetch-retry-mintimeout 20000
            - npm config set fetch-retry-maxtimeout 120000
            - npm config set fetch-retries 5
            - npm config set registry https://registry.npmjs.org/
            - npm ci --prefer-offline --no-audit --no-fund --legacy-peer-deps --network-timeout=100000 || npm install --prefer-offline --no-audit --no-fund --legacy-peer-deps --network-timeout=100000
            - echo "Starting Build"
            - npm run build
            - echo "Copying built files"
            - echo "Build completed"
          artifacts:
            - dist/**
          after-script:
            - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"✅ Thunai Brain Build step completed successfully!\"}' $SLACK_WEBHOOK_URL"
      - step:
          name: Deploying to GCP
          deployment: Production
          script:
            - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"🚚 Thunai Brain Deployment to GCP started...\"}' $SLACK_WEBHOOK_URL"
            - echo "Starting deployment to GCP (Production)"
            - chmod 400 ai-server-gcp.pem
            - echo "Cleaning previous deployment files"
            - ssh -i "ai-server-gcp.pem" -o StrictHostKeyChecking=no gcpubuntu@34.11.2.7 'rm -rf /home/gcpubuntu/dist'
            - echo "Creating deployment directory"
            - ssh -i "ai-server-gcp.pem" -o StrictHostKeyChecking=no gcpubuntu@34.11.2.7 'mkdir -p /home/gcpubuntu/dist'
            - echo "Copying build artifacts to GCP"
            - scp -i "ai-server-gcp.pem" -o StrictHostKeyChecking=no -r dist/* gcpubuntu@34.11.2.7:/home/gcpubuntu/dist/
            - echo "Copying files to /var/www/html"
            - ssh -i "ai-server-gcp.pem" -o StrictHostKeyChecking=no gcpubuntu@34.11.2.7 'sudo cp -r /home/gcpubuntu/dist/* /var/www/html/'
            - echo "Build deployed successfully to GCP (Production)"
          after-script:
            - "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"🚀 Thunai Brain GCP step completed successfully!\"}' $SLACK_WEBHOOK_URL"